version: '3.8'

services:            
  api:
    image: company.api
    build:
      dockerfile: src/Company.Api/Dockerfile
    container_name: company.api 
    networks:
      online-network:
        aliases:
            - company.api
  
  db:
    image: mariadb:10.2
    ports:
        - 3306:3306 
    expose:
        - 3306
    environment: 
        MYSQL_ROOT_HOST: '%'
        MYSQL_ROOT_PASSWORD: nzdBCBuyDKm4y34B
        MYSQL_DATABASE: company_db
        MYSQL_USER: sql7338884
        MYSQL_PASSWORD: K8esL8GKaw
        MYSQL_PORT: 3306
    volumes:
        - company.db-data:/var/lib/mysql
    container_name: company_db
    networks:
      online-network:
        aliases:
            - company.db

volumes:
  company.db-data:
    name: company_db-data
    driver: local